version: '3'
services:
  app:
    build: 
      context: .
    environment:
      DATABASE_HOST:       db
      DATABASE_USER:       postgres
      DATABASE_PASS:       postgres
      DATABASE_NAME:       ${DATABASE_NAME}
      RAILS_ENV:           ${RAILS_ENV}
      RAILS_LOG_TO_STDOUT: ${RAILS_LOG_TO_STDOUT}
      SEED:                ${SEED}
      MIGRATE:             ${MIGRATE}

    volumes:
      - ./:/app/
    ports:
      - 3000:3000
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - db_data:/var/lib/postgresql/data
    # You can export a port to access db outside container.
    # Use a different port to avoid conflict with existing process.
    # ports:
    #   - 5433:5432

volumes:
  db_data:
