# frozen_string_literal: true

default: &default
  adapter:  postgresql
  encoding: utf8
  pool:     <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASS'] %>
  host:     <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  port:     <%= ENV.fetch('DATABASE_PORT') { 5432 }.to_i %>

test:
  <<: *default

development:
  <<: *default

staging:
  <<: *default

production:
  <<: *default


